### ISSUE TITLE
Allow scalar and base precomputations to be done separately

### ISSUE THREAD

**Issue by daira** [zkcrypto/group#34]
There is currently no public API in `Wnaf` to do the precomputations for the scalar and for the base separately. There should be no obstacle to allowing that because the precomputations are independent. That would be precisely what we need to avoid excess computation and allocation when doing scalar muls for the cross product of a set of scalars and a set of bases. (See https://github.com/zcash/librustzcash/issues/593.)

_Originally posted by @daira in https://github.com/zkcrypto/group/pull/33#pullrequestreview-1098773231_

**Comment by str4d** [comment]
Closed by #35 and #36.
