### ISSUE TITLE
Can I transform something from "G1Projective " to "<G as PrimeCurveAffine>::Curve"?

### ISSUE THREAD

**Issue by huapengcheng** [zkcrypto/group#39]
I want to make that something whose struct is "<G as PrimeCurveAffine>::Curve" can be transmitted between differernt processes.But now I just be able to transmitted some "double" things.It may be able to transmit some "u64" things.So I want to get all "u64" in "<G as PrimeCurveAffine>::Curve".And then I can use them to form a "G1Projective" and transform it to get a "<G as PrimeCurveAffine>::Curve".Why I choose "G1Projective" is that I printf some "<G as PrimeCurveAffine>::Curve" and get following results:
![image](https://user-images.githubusercontent.com/88694422/197119819-8988a6f6-3869-4502-bbd1-2ecf4dda8921.png)

**Comment by huapengcheng** [comment]
Or I want to know how to get "u64"s in a "<G as PrimeCurveAffine>::Curve" and how to assign "u64"s to a  "<G as PrimeCurveAffine>::Curve" which is created by myself.

**Comment by str4d** [comment]
The internal representation of a `Group` or `Curve` implementation is not something that gets exposed by the `group` traits. If you need to move an arbitrary generic type that implements `Curve` between processes, you should encode it to bytes with the `GroupEncoding` implementation, pass that encoding between processes, and then parse it back into the type. If you need to pass a point over in a different encoding, you will need to be aware of the concrete type of that point, which means you would be using APIs provided by the concrete implementation, not the `group` crate.

**Comment by str4d** [comment]
Side-note: if you know that you are dealing with specifically elliptic curve points, then the APIs we are thinking about for #30 may be an alternative. But there you would still only get generic field elements that you'd then encode to bytes, so you're generally better off just encoding the points directly with `GroupEncoding`.
